version: '3.7'

services:
  redis:
    restart: always
    image: ${SERVICE_IMAGE_REGISTRY}/whatwewant/redis:${SERVICE_REDIS_VERSION}
    ports:
      - ${SERVICE_REDIS_HOST}:${SERVICE_REDIS_PORT}:6379
    command: redis-server --requirepass $SERVICE_REDIS_SECRET
    volumes:
      - type: bind
        source: ${SERVICE_DATA}
        target: /data
    mem_limit: ${SERVICE_REDIS_RESOURCE_LIMIT_MEM}
    cpus: ${SERVICE_REDIS_RESOURCE_LIMIT_CPU}

networks:
  default:
    external: true
    name: compose-ingress
